### ISSUE TITLE
Failed to install initrafms for dracut-102

### ISSUE THREAD

**Issue by pvalena** [dracut-ng/dracut-ng#334] opened 2024-06-05 03:13 UTC
**Describe the bug**
On Fedora, when testing [WIP upgrade to 102](https://github.com/redhat-plumbers/dracut-fedora/pull/28/commits), I'm 
 - not getting correct initrd built/rebuilt when running `dnf update`
 - not able to boot afterwards, with the just built initrd (for current kernel); with automatic fallback **(with explicit selection suceeds)**

_Note: I hope this is not grubby issue. Posting just to keep everyone in loop. I will try to revert recent `install.d` changes and reproduce again._

Workaround is to build the initrd manually, after booting to (3rd) older kernel -
that is, after manual initrd build using `--kver=...` **with the missing initrd for new kernel** (6.8.11), boot succeeds. Afterwards even the boot using older kernel (6.8.9) succeeds
 - AFAICT problem is the missing initrd.

Logs:
 - Build (run manually; should be identical to `dnf update`):  https://gist.github.com/pvalena/46a6194a24a73d172048ae462ac77157
 - Test: https://gist.github.com/pvalena/7c8554c85a882d478ee78953e2778319
 - Repeated build (newer kernel): https://gist.github.com/pvalena/f8315ca4ed42be1651dc78f2334db5b3

(Everything should be default install, I use it only for testing.)

**Distribution used**
Fedora. I've tested both F41 (rawhide) and F40.

**Dracut version**
102

**Init system**
Systemd.

**To Reproduce**
 - Upgrade to newer dracut version, at the same time as new kernel update is installed. (Do not create missing initrd manually.)
 - Reboot.
 - Reboot to 1st older (original) kernel; which was built instead of the new one.

**Expected behavior**
 - New initrd for kernel which was just installed (and is being installed atm) is build instead of the old kernel version.
 - Maybe even the older initrd should be usable? Not sure what happened there.

**Additional context**
https://github.com/dracut-ng/dracut-ng/blob/main/install.d/50-dracut.install#L4

```
KERNEL_VERSION="${2:?}"
```
Is probably not propagated correctly? Or I'm missing something else.

Recent changes:
https://github.com/dracut-ng/dracut-ng/commit/8388ad149c698c951089606352fdb0cdcaaf40c9
https://github.com/dracut-ng/dracut-ng/commit/d40155385d060f8d8608fa8a4931e2e42ddc3a8f

**Comment by pvalena** [comment] 2024-06-05 03:23
Verified - simply removing the latest initrd reproduces the issue:
https://gist.github.com/pvalena/e89f51897bbf5ed20ab3b367ce6af808

But booting explicitly to older kernel (even 6.8.9) succeeds.

Please note that kernel versions are for this case - reference - only, and does not really matter.

**Comment by LaszloGombos** [comment] 2024-06-09 22:26
CC @AndrewAmmerlaan for visibility

**Comment by AndrewAmmerlaan** [comment] 2024-06-10 04:54
Please add the log from `dnf update` as well.

None of the provided logs appear to be using kernel-install or the 50-dracut.install hook. When --kver is not specified (as in the first log) dracut defaults to the running kernel, so the behaviour you are seeing is expected.

**Comment by AndrewAmmerlaan** [comment] 2024-06-10 14:07
> Even before the v102 update, there seems to be some pre-existing (v60) issues with 50-dracut.install hook in Fedora - e.g. https://bugzilla.redhat.com/show_bug.cgi?id=2280058

This should be resolved in 102 since we don't write to `/boot` or `/efi` directly but to the staging area instead.

**Comment by pvalena** [comment] 2024-06-12 04:27
> Please add the log from `dnf update` as well.

There's nothing useful there - it's a generic [package install log](https://gist.github.com/pvalena/88a43b12100eb719be259b7256a738e7). 

> None of the provided logs appear to be using kernel-install or the 50-dracut.install hook. When --kver is not specified (as in the first log) dracut defaults to the running kernel, so the behaviour you are seeing is expected.

`dnf` doesn't seem to log the scriplet output anywhere AFAICT - even when `--debuglevel` / `--verbose` are set; and it's not in `/var/log/dnf.log` either.

I can confirm this is a dracut bug, because when I downgrade to `dracut-101` everything works as expected ([log](https://gist.github.com/pvalena/566759d18c05f20dc030988391697533)).

**Comment by pvalena** [comment] 2024-06-12 05:52
Specifically, reverting this commit resolves the issue: https://github.com/dracut-ng/dracut-ng/commit/d40155385d060f8d8608fa8a4931e2e42ddc3a8f

([test log](https://gist.github.com/pvalena/836351ee3b2a5cf3aa7121de7782735d))

**Comment by AndrewAmmerlaan** [comment] 2024-06-12 09:08
The first logs you shared show:
```
dracut[I]: Executing: /usr/bin/dracut -f -vvv
```
And:
```
dracut[I]: Executing: /usr/bin/dracut -f -vvv --kver=6.8.11-300.fc40.x86_64
```
When `--kver` is not specified then `uname -r` is assumed, so it makes sense that it would generate the initramfs for the currently running kernel and not the kernel you are upgrading to.

In `50-dracut.install` we have:
```
dracut -f \
    ${noimageifnotneeded:+--noimageifnotneeded} \
    $([[ $KERNEL_INSTALL_VERBOSE == 1 ]] && echo --verbose) \
    $([[ -n $KERNEL_IMAGE ]] && echo --kernel-image "$KERNEL_IMAGE") \
    "$UEFI_OPTS" \
    --kver "$KERNEL_VERSION" \
    "$KERNEL_INSTALL_STAGING_AREA/$IMAGE" || exit 1
```
This does not match with the dracut arguments from your logs, this indicates to me that the plugin is not used in those logs.

I don't know how Fedora installs the kernel exactly, but the main change between 101 and 102 is that the "fallback path" that was causing a bunch of problems was removed, and the `KERNEL_INSTALL_STAGING_AREA` is used always. It is the responsibility of some other kernel-install plugin to take the `initrd` from the `KERNEL_INSTALL_STAGING_AREA` and install it to the proper location depending on `KERNEL_INSTALL_LAYOUT`. For GRUB this would be `/boot`, but for systemd-boot this would for example be installed in a different place. This is the point of the staging area. What might be happening (but it is not easy to see from your logs since it does not run `--verbose`) is that `50-dracut.install` puts the initramfs on the staging area (as it should) but that later on this initramfs is not installed.

To be sure I would need the output of:
```
kernel-install add KERNEL-VERSION KERNEL-IMAGE --verbose
```
And a list of kernel-install plugins that are installed:
```
ls -l /usr/lib/kernel/install.d
ls -l /etc/kernel/install.d
```
And the contents of the `kernel-install` configuration file:
```
cat /usr/lib/kernel/install.conf
cat /etc/kernel/install.conf
```

**Comment by pvalena** [comment] 2024-06-12 11:56
@AndrewAmmerlaan, thanks for taking time to write the response.

> This does not match with the dracut arguments from your logs, this indicates to me that the plugin is not used in those logs.


Yes, those logs are from what I have invoked manually, just as an example, to show "dracut works".
The issue occurs only when invoked via the `install.d/` script. The manual runs are not representative of the issue, but of the working state.

> I don't know how Fedora installs the kernel exactly, but the main change between 101 and 102 is that the "fallback path" that was causing a bunch of problems was removed, and the `KERNEL_INSTALL_STAGING_AREA` is used always. It is the responsibility of some other kernel-install plugin to take the `initrd` from the `KERNEL_INSTALL_STAGING_AREA` and install it to the proper location depending on `KERNEL_INSTALL_LAYOUT`. For GRUB this would be `/boot`, but for systemd-boot this would for example be installed in a different place. This is the point of the staging area. What might be happening (but it is not easy to see from your logs since it does not run `--verbose`) is that `50-dracut.install` puts the initramfs on the staging area (as it should) but that later on this initramfs is not installed.

FTR In Fedora, the kernel-install is invoked as such: https://src.fedoraproject.org/rpms/kernel/blob/rawhide/f/kernel.spec#_3529

That seems to be the issue; sorry, I should've included these in the first place, but it didn't occur to me I can just invoke those manually.

Log with the 2 commits:
 - reverted (working state): https://gist.github.com/pvalena/33d6d36b085b1fd823f5f15403a6c6dc
 - applied (issue reproduced): https://gist.github.com/pvalena/430d0c9eb0888d8b2a9025abea3085aa

Strange, it ends with the message image is in `/tmp/kernel-install.staging.xKvK2a/initrd` - but there's no image afterwards. Neither it's in `/boot`.

> ```
> cat /usr/lib/kernel/install.conf
> cat /etc/kernel/install.conf
> ```

All files included in the first log; all are the system defaults. Please note that this **is reproducible** on all of Fedoras that I've tried.

**Comment by AndrewAmmerlaan** [comment] 2024-06-12 14:05
> Strange, it ends with the message image is in /tmp/kernel-install.staging.xKvK2a/initrd - but there's no image afterwards. Neither it's in /boot.

This is expected, the staging area is cleared after successful execution.

It seems the issue is indeed what I thought it was, the image is generated but not installed. Fedora relied on this fallback path that we removed.

I see you have `20-grub.install`: https://src.fedoraproject.org/rpms/grub2/blob/rawhide/f/20-grub.install which actually does most of the installing for GRUB. I think the best solution is to either:
- Adjust `20-grub.install` so it not only installs the kernel image, but also grabs the `initrd` from the staging area and installs it. This would then have to be adjusted to run after `50-dracut.install`. IMO this makes the most sense, because the plugin is also making a bls entry file, and it makes sense to only create this file if the kernel and initrd are actually successfully installed.
- Or, add a new kernel-install hook (e.g. `60-install-initrd`) which does the above.

For reference, this is the Gentoo hook that installs the inird/uki/kernel-image for GRUB: https://github.com/projg2/installkernel-gentoo/blob/master/hooks/systemd/90-compat.install

**Comment by LaszloGombos** [comment] 2024-06-30 17:47
@pvalena I am wondering if you would agree to close this bug upstream as it seems this issue only needs attention downstream. Thanks !

**Comment by pvalena** [comment] 2024-07-01 07:59
I agree, as this does not affect upstream (when upstream does not care about breaking changes), I'm fine with closing the bug.

**Closed** 2024-07-01 08:02 UTC
Labels: bug

**Comment by LaszloGombos** [comment] 2024-07-11 16:04
CC @DaanDeMeyer for visibility

**Comment by DaanDeMeyer** [comment] 2024-07-18 06:58
I reported https://bugzilla.redhat.com/show_bug.cgi?id=2298576 for the grub2 package to hopefully get 20-grub.install fixed.
