### ISSUE TITLE
Gentoo container no longer builds

### ISSUE THREAD

**Issue by jozzsi** [dracut-ng/dracut-ng#772] opened 2024-10-21 16:56 UTC
https://github.com/dracut-ng/dracut-ng/actions/runs/11439291407

Likely started yesterday, fairly recent (but different than the last one).

CC @Nowa-Ammerlaan

**Comment by Nowa-Ammerlaan** [comment] 2024-10-21 17:19
```
#17 1939.0 configure: error: Package requirements (pangocairo >= 1.21.0 ) were not met:
#17 1939.0 
#17 1939.0 Package 'xproto', required by 'xrender', not found
#17 1939.0 Package 'renderproto', required by 'xrender', not found
#17 1939.0 Package 'xproto', required by 'x11', not found
#17 1939.0 Package 'kbproto', required by 'x11', not found
#17 1939.0 Package 'xproto', required by 'xft', not found
#17 1939.0 Package 'xextproto', required by 'xext', not found
#17 1939.0 Package 'xproto', required by 'xau', not found
#17 1939.0 Package 'xproto', required by 'xdmcp', not found
```

Looks like the same underlying problem.

I do not understand this, plymouth locally builds fine for me, and the CI on our end has not reported a new build failure.

@prometheanfire could you maybe help out here?

**Comment by Nowa-Ammerlaan** [comment] 2024-10-21 17:33
Okay never mind, I had a dumb moment. The issue is exposed due to pango being merged as a binary package here, and therefore it's build dependencies (specifically xorg-proto) are not pulled into the dependency graph. This uncovers that xorg-proto is also a build dependency of plymouth. Fixed now (for real this time :P): https://github.com/gentoo/gentoo/commit/64bbb97132d0c1673b3f6fda568f3c2c2ac3debd

**Closed by Nowa-Ammerlaan** 2024-10-21 17:33 UTC
Labels: bug

**Comment by Nowa-Ammerlaan** [comment] 2024-10-22 07:28
It seems to be working now: https://github.com/dracut-ng/dracut-ng/actions/runs/11452272640/job/31862873982

It's now pulling xorg-proto into the docker image.
