### ISSUE TITLE
Gentoo CI container fails to build

### ISSUE THREAD

**Issue by jozzsi** [dracut-ng/dracut-ng#630] opened 2024-08-31 12:40 UTC
https://github.com/dracut-ng/dracut-ng/actions/runs/10644916381

@AndrewAmmerlaan can you please help to check if this would require a PR or expected to recover over time ? Thanks !

**Comment by AndrewAmmerlaan** [comment] 2024-08-31 13:17
Caused by: https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass/kernel-build.eclass?id=660b9cf9f08fd27fca32f1bd1bd8e95ee7a635bc

Should be resolved by: https://github.com/dracut-ng/dracut-ng/pull/631

**Closed** 2024-08-31 14:20 UTC
Labels: bug
